# Generated by Django 3.2.7 on 2021-09-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('line', models.CharField(max_length=150)),
                ('geo_location', models.CharField(max_length=150)),
            ],
        ),
    ]
